int ftp_connect( char *host, int port, char *user, char *pwd );
int ftp_quit( int c_sock);
int ftp_type( int c_sock, char mode );
int ftp_cwd( int c_sock, char *path );
int ftp_cdup( int c_sock );
int ftp_mkd( int c_sock, char *path );
int ftp_list( int c_sock, char *path, void **data, unsigned long long *data_len);
int ftp_retrfile( int c_sock, char *s, char *d ,unsigned long long *stor_size, int *stop);
int ftp_storfile( int c_sock, char *s, char *d ,unsigned long long *stor_size, int *stop);
int ftp_renamefile( int c_sock, char *s, char *d );
int ftp_deletefile( int c_sock, char *s );
int ftp_deletefolder( int c_sock, char *s );
int termiosCh() ;
int inputArrlist(char *arr, int size,int flag);
